### ISSUE TITLE
UINavigationController.hidesBottomBarWhenPushed is not handled?

### ISSUE THREAD

**Issue by fprosper** [jinthagerman/JBTabBarController#4]
Another question, wondering if this can be done or if I need to find a way to hide the bar myself. Thanks.

**Comment by jinthagerman** [comment]
I will look into implementing this natively in JBTabBarController, but it looks like it will take a fair amount of effort if it is in fact possible.

You will need to do this manually for now. You should be able to achieve this fairly easily animating the frame of the JBTabBar and the frame of the navController in viewDidAppear or viewWillAppear and viewDidDisappear or viewWillDisappear.

**Comment by jinthagerman** [comment]
or implement the [UINavigationControllerDelegate Protocol](http://developer.apple.com/library/ios/#documentation/uikit/reference/UINavigationControllerDelegate_Protocol/Reference/Reference.html) and animate the views in navigationController:willShowViewController:animated: or navigationController:didShowViewController:animated:

**Comment by fprosper** [comment]
Not sure we are on the same page on this: the  'hidesBottomBarWhenPushed' method is meant to hide the bottom bar (in this case the UITabBar when the view controller is pushed on the navigation stack, no animation involved. 

Thanks,
F.

## 

Fabrizio Prosperi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jinthagerman** [comment]
I haven't used `hidesBottomBarWhenPushed` before, but my understanding of it matches what you have said.

When you push a view controller with `hidesBottomBarWhenPushed` set onto the nav stack, does it not animate the hiding of the "bottom bar"/`UITabBar`? That is what I meant by animation in the comment above. If you simply want to hide it without any animation, just set `tabBar.hidden` to YES and resize the `selectedViewController`'s `view`.

Might be worth checking out this guy's fork of `BCTabBarController` and applying the same thing to `JBTabBarController`.
https://github.com/xuzhe/BCTabBarController/commit/467ae076a8eab96f9702a6ddd00fa6f9ecf84f4b

**Comment by fprosper** [comment]
Thanks, halfway there. Managed to hide tabBar in viewDidLoad but can't seem to resize self.view with:
- (void)viewDidLoad 
  {
  [super viewDidLoad];
  self.navigationController.JBTabBarController.tabBar.hidden = YES;
  self.view.frame = CGRectMake(0, 0, 320, 460);
  }

Maybe viewDidLoad is too late, but in initWithFrame the tabBar is not accessible yet.

F.

## 

Fabrizio Prosperi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jinthagerman** [comment]
I wouldn't recommend doing it in viewDidLoad, but if you replace the third line with `self.navigationController.view.frame = CGRectMake(0, 0, 320, 460);` it should work.

**Comment by fprosper** [comment]
Thank you very much Jin, it worked. 

F. 

## 

Fabrizio Prosperi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jinthagerman** [comment]
No problem
