### ISSUE TITLE
Example without JRSizzle?

### ISSUE THREAD

**Issue by damassi** [jinthagerman/JBTabBarController#5]
Wondering if you could provide an example implementation that does not use JRSizzle?  I have a use-case that prohibits it.

**Comment by jinthagerman** [comment]
Just don't include UINavigationController+JBAdditions.h and UINavigationController+JBAdditions.m

All this means is that the JBTabBarController will only assign itself as the JBTabBarController property on the root UIViewController for each tab. This means if you want to access the JBTabBarController from within a tab's UIViewController hierarchy, you will need to find your way back to the root UIViewController for the tab you are in.

For example:

```
JBTabBarController *tabBarController = self.navigationController.JBTabBarController;
```

**Comment by damassi** [comment]
Excellent, thank you very much.
