### ISSUE TITLE
what can i do JBTabBar hide 

### ISSUE THREAD

**Issue by jiangmingz** [jinthagerman/JBTabBarController#7]
JBTabBar can hide ?

**Comment by jinthagerman** [comment]
Do you want to hide it animated or just hide it?

**Comment by jiangmingz** [comment]
Yes,I used UINavigationController, push  a UIViewController, I want to hide  JBTabBar

**Comment by jinthagerman** [comment]
Take a look at this issue https://github.com/jinthagerman/JBTabBarController/issues/4

I would recommend you animate the frame of the JBTabBar in the view controller's viewWillAppear method.

**Comment by jiangmingz** [comment]
i know, thanks
